[package]
name = "percival"
version = "0.1.0"
authors = ["Eric Zhang <ekzhang1@gmail.com>"]
edition = "2021"

[dependencies]
ariadne = "0.1.3"
chumsky = "0.6.0"
maplit = "1.0.2"
rpds = "0.10.0"
thiserror = "1.0.30"
