[package]
name = "percival"
version = "0.1.0"
authors = ["Eric Zhang <ekzhang1@gmail.com>"]
edition = "2021"

[dependencies]
ariadne = "0.1.5"
chumsky = "0.8.0"
rpds = "0.12.0"
thiserror = "1.0.30"

[dev-dependencies]
maplit = "1.0.2"
