[package]
name = "percival-cli"
version = "0.1.0"
authors = ["Eric Zhang <ekzhang1@gmail.com>"]
edition = "2021"

[dependencies]
chumsky = "0.6.0"
percival = { path = "../percival" }
structopt = "0.3.25"
